import { RawRecord } from "./types";

// 120+ Unique Deterministic RS Puram Restaurants
const RS_PURAM_RESTAURANTS: RawRecord[] = [
  {
    business_name: "Annapoorna Gowrishankar",
    category: "Restaurant",
    sub_category: "Vegetarian",
    phone: "+91 422 244 5566",
    phone_raw: "+914222445566",
    website: null,
    address: "456 DB Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.7,
    reviews: 2100,
    scraped_at: "2025-01-15T10:31:00Z",
    place_id: "ChIJ_RSP_REST_001",
    social_links: ["https://facebook.com/annapoorna"],
  },
  {
    business_name: "Sree Annapoorna Sree Gowrishankar",
    category: "Restaurant",
    sub_category: "South Indian",
    phone: "+91 422 244 5502",
    phone_raw: "+914222445502",
    website: "https://annapoorna.com",
    address: "12 East TV Swamy Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.6,
    reviews: 1560,
    scraped_at: "2025-01-15T10:32:00Z",
    place_id: "ChIJ_RSP_REST_002",
    social_links: ["https://instagram.com/annapoorna"],
  },
  {
    business_name: "Shree Anandhaas Restaurant",
    category: "Restaurant",
    sub_category: "Vegetarian & Sweets",
    phone: "+91 422 244 5503",
    phone_raw: "+914222445503",
    website: null,
    address: "78 DB Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.5,
    reviews: 1840,
    scraped_at: "2025-01-15T10:33:00Z",
    place_id: "ChIJ_RSP_REST_003",
    social_links: ["https://facebook.com/shreeanandhaas"],
  },
  {
    business_name: "Haribhavanam Restaurant",
    category: "Restaurant",
    sub_category: "Chettinad & Non-Veg",
    phone: "+91 422 244 5504",
    phone_raw: "+914222445504",
    website: "https://haribhavanam.in",
    address: "102 East TV Swamy Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.6,
    reviews: 2300,
    scraped_at: "2025-01-15T10:34:00Z",
    place_id: "ChIJ_RSP_REST_004",
    social_links: ["https://instagram.com/haribhavanam"],
  },
  {
    business_name: "Junior Kuppanna RS Puram",
    category: "Restaurant",
    sub_category: "Kongu Non-Veg",
    phone: "+91 422 244 5505",
    phone_raw: "+914222445505",
    website: null,
    address: "54 West TV Swamy Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.3,
    reviews: 1120,
    scraped_at: "2025-01-15T10:35:00Z",
    place_id: "ChIJ_RSP_REST_005",
    social_links: [],
  },
  {
    business_name: "Saravana Bhavan RS Puram",
    category: "Restaurant",
    sub_category: "South Indian",
    phone: "+91 422 244 5506",
    phone_raw: "+914222445506",
    website: "https://saravanabhavan.com",
    address: "89 Diwan Bahadur Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.4,
    reviews: 980,
    scraped_at: "2025-01-15T10:36:00Z",
    place_id: "ChIJ_RSP_REST_006",
    social_links: ["https://facebook.com/saravanabhavan"],
  },
  {
    business_name: "Achi Mess Chettinad",
    category: "Restaurant",
    sub_category: "Chettinad",
    phone: "+91 422 244 5507",
    phone_raw: "+914222445507",
    website: null,
    address: "33 Lawley Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.2,
    reviews: 640,
    scraped_at: "2025-01-15T10:37:00Z",
    place_id: "ChIJ_RSP_REST_007",
    social_links: [],
  },
  {
    business_name: "Dindigul Thalappakatti Restaurant",
    category: "Restaurant",
    sub_category: "Biryani & Non-Veg",
    phone: "+91 422 244 5508",
    phone_raw: "+914222445508",
    website: "https://thalappakatti.com",
    address: "67 DB Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.3,
    reviews: 1450,
    scraped_at: "2025-01-15T10:38:00Z",
    place_id: "ChIJ_RSP_REST_008",
    social_links: ["https://instagram.com/thalappakatti"],
  },
  {
    business_name: "The French Door Cafe & Restaurant",
    category: "Restaurant",
    sub_category: "European & Bistro",
    phone: "+91 422 244 5509",
    phone_raw: "+914222445509",
    website: null,
    address: "14 West Club Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.8,
    reviews: 890,
    scraped_at: "2025-01-15T10:39:00Z",
    place_id: "ChIJ_RSP_REST_009",
    social_links: ["https://instagram.com/thefrenchdoor"],
  },
  {
    business_name: "Cascade Chinese Restaurant",
    category: "Restaurant",
    sub_category: "Chinese & Asian",
    phone: "+91 422 244 5510",
    phone_raw: "+914222445510",
    website: "https://cascaderestaurant.com",
    address: "220 DB Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.5,
    reviews: 1020,
    scraped_at: "2025-01-15T10:40:00Z",
    place_id: "ChIJ_RSP_REST_010",
    social_links: [],
  },
  {
    business_name: "Barbeque Nation RS Puram",
    category: "Restaurant",
    sub_category: "Buffet & Grill",
    phone: "+91 422 244 5511",
    phone_raw: "+914222445511",
    website: "https://barbequenation.com",
    address: "15 Cowley Brown Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.4,
    reviews: 1780,
    scraped_at: "2025-01-15T10:41:00Z",
    place_id: "ChIJ_RSP_REST_011",
    social_links: ["https://facebook.com/barbequenation"],
  },
  {
    business_name: "That's Y Food",
    category: "Restaurant",
    sub_category: "North Indian & Continental",
    phone: "+91 422 244 5512",
    phone_raw: "+914222445512",
    website: null,
    address: "24 East TV Swamy Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.6,
    reviews: 1350,
    scraped_at: "2025-01-15T10:42:00Z",
    place_id: "ChIJ_RSP_REST_012",
    social_links: ["https://instagram.com/thatsyfood"],
  },
  {
    business_name: "On The Go Fine Dining",
    category: "Restaurant",
    sub_category: "Multi-Cuisine",
    phone: "+91 422 244 5513",
    phone_raw: "+914222445513",
    website: "https://onthego.co.in",
    address: "167 DB Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.5,
    reviews: 920,
    scraped_at: "2025-01-15T10:43:00Z",
    place_id: "ChIJ_RSP_REST_013",
    social_links: [],
  },
  {
    business_name: "Kowloon Restaurant",
    category: "Restaurant",
    sub_category: "Chinese",
    phone: "+91 422 244 5514",
    phone_raw: "+914222445514",
    website: null,
    address: "42 Diwan Bahadur Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.2,
    reviews: 580,
    scraped_at: "2025-01-15T10:44:00Z",
    place_id: "ChIJ_RSP_REST_014",
    social_links: [],
  },
  {
    business_name: "Zucca Pizzeria & Bistro",
    category: "Restaurant",
    sub_category: "Italian",
    phone: "+91 422 244 5515",
    phone_raw: "+914222445515",
    website: null,
    address: "19 West Club Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.4,
    reviews: 730,
    scraped_at: "2025-01-15T10:45:00Z",
    place_id: "ChIJ_RSP_REST_015",
    social_links: ["https://instagram.com/zuccapizzeria"],
  },
  {
    business_name: "Cafe Totaram",
    category: "Restaurant",
    sub_category: "North Indian & Snacks",
    phone: "+91 422 244 5516",
    phone_raw: "+914222445516",
    website: null,
    address: "81 DB Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.3,
    reviews: 670,
    scraped_at: "2025-01-15T10:46:00Z",
    place_id: "ChIJ_RSP_REST_016",
    social_links: [],
  },
  {
    business_name: "Cream Centre RS Puram",
    category: "Restaurant",
    sub_category: "Vegetarian Bistro",
    phone: "+91 422 244 5517",
    phone_raw: "+914222445517",
    website: "https://creamcentre.com",
    address: "95 East TV Swamy Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.3,
    reviews: 840,
    scraped_at: "2025-01-15T10:47:00Z",
    place_id: "ChIJ_RSP_REST_017",
    social_links: ["https://facebook.com/creamcentre"],
  },
  {
    business_name: "Little Italy Kovai",
    category: "Restaurant",
    sub_category: "Italian & Mexican",
    phone: "+91 422 244 5518",
    phone_raw: "+914222445518",
    website: "https://littleitaly.in",
    address: "52 West TV Swamy Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.5,
    reviews: 1150,
    scraped_at: "2025-01-15T10:48:00Z",
    place_id: "ChIJ_RSP_REST_018",
    social_links: ["https://instagram.com/littleitalykovai"],
  },
  {
    business_name: "Barani Chettinad Mess",
    category: "Restaurant",
    sub_category: "Chettinad",
    phone: "+91 422 244 5519",
    phone_raw: "+914222445519",
    website: null,
    address: "11 McIver Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.1,
    reviews: 490,
    scraped_at: "2025-01-15T10:49:00Z",
    place_id: "ChIJ_RSP_REST_019",
    social_links: [],
  },
  {
    business_name: "Selvi Mess RS Puram",
    category: "Restaurant",
    sub_category: "Traditional Kongu",
    phone: "+91 422 244 5520",
    phone_raw: "+914222445520",
    website: null,
    address: "38 Light House Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.4,
    reviews: 820,
    scraped_at: "2025-01-15T10:50:00Z",
    place_id: "ChIJ_RSP_REST_020",
    social_links: [],
  },
  {
    business_name: "RHR Restaurant",
    category: "Restaurant",
    sub_category: "Pure Vegetarian",
    phone: "+91 422 244 5521",
    phone_raw: "+914222445521",
    website: null,
    address: "112 DB Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.2,
    reviews: 950,
    scraped_at: "2025-01-15T10:51:00Z",
    place_id: "ChIJ_RSP_REST_021",
    social_links: [],
  },
  {
    business_name: "Idly Virundhu",
    category: "Restaurant",
    sub_category: "Tiffin & Breakfast",
    phone: "+91 422 244 5522",
    phone_raw: "+914222445522",
    website: null,
    address: "47 Diwan Bahadur Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.3,
    reviews: 510,
    scraped_at: "2025-01-15T10:52:00Z",
    place_id: "ChIJ_RSP_REST_022",
    social_links: [],
  },
  {
    business_name: "Gowri Krishna Hotel",
    category: "Restaurant",
    sub_category: "South Indian Veg",
    phone: "+91 422 244 5523",
    phone_raw: "+914222445523",
    website: null,
    address: "63 East TV Swamy Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.1,
    reviews: 620,
    scraped_at: "2025-01-15T10:53:00Z",
    place_id: "ChIJ_RSP_REST_023",
    social_links: [],
  },
  {
    business_name: "Nalabagam Mess",
    category: "Restaurant",
    sub_category: "Home Style Meals",
    phone: "+91 422 244 5524",
    phone_raw: "+914222445524",
    website: null,
    address: "29 Cowley Brown Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.4,
    reviews: 430,
    scraped_at: "2025-01-15T10:54:00Z",
    place_id: "ChIJ_RSP_REST_024",
    social_links: [],
  },
  {
    business_name: "Kongu Mess Traditional",
    category: "Restaurant",
    sub_category: "Kongunadu Cuisine",
    phone: "+91 422 244 5525",
    phone_raw: "+914222445525",
    website: null,
    address: "18 Lawley Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.5,
    reviews: 970,
    scraped_at: "2025-01-15T10:55:00Z",
    place_id: "ChIJ_RSP_REST_025",
    social_links: [],
  },
  {
    business_name: "Madurai Sri Muniyandi Vilas",
    category: "Restaurant",
    sub_category: "Madurai Non-Veg",
    phone: "+91 422 244 5526",
    phone_raw: "+914222445526",
    website: null,
    address: "73 West TV Swamy Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.2,
    reviews: 690,
    scraped_at: "2025-01-15T10:56:00Z",
    place_id: "ChIJ_RSP_REST_026",
    social_links: [],
  },
  {
    business_name: "Biryani Hub RS Puram",
    category: "Restaurant",
    sub_category: "Hyderabadi Biryani",
    phone: "+91 422 244 5527",
    phone_raw: "+914222445527",
    website: null,
    address: "145 DB Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.1,
    reviews: 580,
    scraped_at: "2025-01-15T10:57:00Z",
    place_id: "ChIJ_RSP_REST_027",
    social_links: [],
  },
  {
    business_name: "Smoke Hub Barbeque",
    category: "Restaurant",
    sub_category: "Barbecue & Grill",
    phone: "+91 422 244 5528",
    phone_raw: "+914222445528",
    website: "https://smokehub.in",
    address: "88 Diwan Bahadur Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.3,
    reviews: 1100,
    scraped_at: "2025-01-15T10:58:00Z",
    place_id: "ChIJ_RSP_REST_028",
    social_links: ["https://instagram.com/smokehub"],
  },
  {
    business_name: "Afghan Grill & Tandoor",
    category: "Restaurant",
    sub_category: "Mughlai & Afghan",
    phone: "+91 422 244 5529",
    phone_raw: "+914222445529",
    website: null,
    address: "31 West Club Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.3,
    reviews: 520,
    scraped_at: "2025-01-15T10:59:00Z",
    place_id: "ChIJ_RSP_REST_029",
    social_links: [],
  },
  {
    business_name: "Beijing Bites Chinese",
    category: "Restaurant",
    sub_category: "Chinese & Thai",
    phone: "+91 422 244 5530",
    phone_raw: "+914222445530",
    website: null,
    address: "92 East TV Swamy Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.0,
    reviews: 460,
    scraped_at: "2025-01-15T11:00:00Z",
    place_id: "ChIJ_RSP_REST_030",
    social_links: [],
  },
  {
    business_name: "Urban Barbecue Kitchen",
    category: "Restaurant",
    sub_category: "Grilled Specialties",
    phone: "+91 422 244 5531",
    phone_raw: "+914222445531",
    website: null,
    address: "105 DB Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.4,
    reviews: 620,
    scraped_at: "2025-01-15T11:01:00Z",
    place_id: "ChIJ_RSP_REST_031",
    social_links: [],
  },
  {
    business_name: "Punjabi Dhaba RS Puram",
    category: "Restaurant",
    sub_category: "North Indian",
    phone: "+91 422 244 5532",
    phone_raw: "+914222445532",
    website: null,
    address: "26 Cowley Brown Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.2,
    reviews: 530,
    scraped_at: "2025-01-15T11:02:00Z",
    place_id: "ChIJ_RSP_REST_032",
    social_links: [],
  },
  {
    business_name: "Tandoori Nights Kovai",
    category: "Restaurant",
    sub_category: "Tandoor & Kebab",
    phone: "+91 422 244 5533",
    phone_raw: "+914222445533",
    website: null,
    address: "61 Diwan Bahadur Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.1,
    reviews: 410,
    scraped_at: "2025-01-15T11:03:00Z",
    place_id: "ChIJ_RSP_REST_033",
    social_links: [],
  },
  {
    business_name: "Royal Biryani Darbar",
    category: "Restaurant",
    sub_category: "Mughlai Biryani",
    phone: "+91 422 244 5534",
    phone_raw: "+914222445534",
    website: null,
    address: "44 West TV Swamy Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.3,
    reviews: 790,
    scraped_at: "2025-01-15T11:04:00Z",
    place_id: "ChIJ_RSP_REST_034",
    social_links: [],
  },
  {
    business_name: "Spice Garden Restaurant",
    category: "Restaurant",
    sub_category: "Multi-Cuisine Family Dining",
    phone: "+91 422 244 5535",
    phone_raw: "+914222445535",
    website: "https://spicegardenkovai.com",
    address: "133 DB Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.5,
    reviews: 1040,
    scraped_at: "2025-01-15T11:05:00Z",
    place_id: "ChIJ_RSP_REST_035",
    social_links: ["https://instagram.com/spicegardenkovai"],
  },
  {
    business_name: "Olive Grill & Mediterranean",
    category: "Restaurant",
    sub_category: "Continental & Grills",
    phone: "+91 422 244 5536",
    phone_raw: "+914222445536",
    website: null,
    address: "8 West Club Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.6,
    reviews: 670,
    scraped_at: "2025-01-15T11:06:00Z",
    place_id: "ChIJ_RSP_REST_036",
    social_links: [],
  },
  {
    business_name: "Curry Leaf Veg Restaurant",
    category: "Restaurant",
    sub_category: "Traditional Pure Veg",
    phone: "+91 422 244 5537",
    phone_raw: "+914222445537",
    website: null,
    address: "71 East TV Swamy Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.3,
    reviews: 580,
    scraped_at: "2025-01-15T11:07:00Z",
    place_id: "ChIJ_RSP_REST_037",
    social_links: [],
  },
  {
    business_name: "Chettinad Kitchen RS Puram",
    category: "Restaurant",
    sub_category: "Chettinad Spicy Meals",
    phone: "+91 422 244 5538",
    phone_raw: "+914222445538",
    website: null,
    address: "39 Light House Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.4,
    reviews: 740,
    scraped_at: "2025-01-15T11:08:00Z",
    place_id: "ChIJ_RSP_REST_038",
    social_links: [],
  },
  {
    business_name: "Malabar Treat Coastal Food",
    category: "Restaurant",
    sub_category: "Kerala & Seafood",
    phone: "+91 422 244 5539",
    phone_raw: "+914222445539",
    website: null,
    address: "51 Lawley Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.3,
    reviews: 620,
    scraped_at: "2025-01-15T11:09:00Z",
    place_id: "ChIJ_RSP_REST_039",
    social_links: [],
  },
  {
    business_name: "Coastal Flavours Seafood",
    category: "Restaurant",
    sub_category: "Seafood Specialty",
    phone: "+91 422 244 5540",
    phone_raw: "+914222445540",
    website: null,
    address: "17 Cowley Brown Road, RS Puram, Coimbatore, Tamil Nadu 641002",
    city: "Coimbatore",
    rating: 4.5,
    reviews: 830,
    scraped_at: "2025-01-15T11:10:00Z",
    place_id: "ChIJ_RSP_REST_040",
    social_links: [],
  },
  // Adding items 41 to 125 deterministically
  ...Array.from({ length: 85 }, (_, i) => {
    const idx = i + 41;
    const names = [
      "Wok & Grill Asian", "Desi Tadka Dining", "Southern Feast Restaurant", "Copper Chimney Flavours",
      "Zaika Darbar", "Chola Royal Dining", "Pallava Treat Mess", "Pandya Kingdom Meals",
      "Kongu Delights Kitchen", "Kovai Tiffin Center", "Western Ghats Kitchen", "Nilgiri Flavours Dining",
      "Siruvani Feast Veg", "Marudham Dining Hall", "Noyyal River Kitchen", "Velliangiri Treat",
      "Kurinji Mountain Kitchen", "Mullai Traditional Dhaba", "Marutham Farm Mess", "Neithal Coastal Dining",
      "Palai Hot Pot", "Thulasi Bhavan Veg", "Vasantha Bhavan Kovai", "Saravana Savouries Dining",
      "Gokulam Vegetarian", "Ganga Grandeur Meals", "Yamuna Dining Hall", "Kaveri Tiffin Corner",
      "Godavari Andhra Mess", "Krishna Bhavan South", "Radha Vilas Tiffin", "Balaji Mess RS Puram",
      "Venkateswara Treat", "Murugan Idli Center", "Meenakshi Bhavan Mess", "Sundaram Mess Veg",
      "Natraj Dining Corner", "Sai Sangeet Veg", "Anbu Mess Chettinad", "Subbu Mess RS Puram",
      "Geetha Canteen", "Muthu Mess NonVeg", "Vasantham Dining", "Lakshmi Vilas Tiffin",
      "Raja Biryani Kitchen", "Sultan Biryani Express", "Nawab Feast Mughlai", "Grand Kovai Kitchen",
      "Heritage Dining Hall", "Village Feast Chettinad", "Country Kitchen RS Puram", "Pepper Pot Restaurant",
      "Golden Spoon Kovai", "Silver Plate Dining", "Flavours of Malabar", "Bamboo Hut Asian",
      "Clay Pot Traditional", "Banana Leaf Feast", "Tava & Clay Kitchen", "Royal Turban Dhaba",
      "Madras Curry House", "Coimbatore Biryani Club", "Dindigul Express", "Ambur Star Treat",
      "Thalassery Spices", "Kozhikode Halwa & Biryani", "Chettinadu Express", "Karaikudi NonVeg Mess",
      "Salem RR Biryani", "Erode Kongu Virundhu", "Tirupur Tiffin House", "Pollachi Coconut Feast",
      "Udumalai Mutton Mess", "Palani Murugan Tiffin", "Madurai Pandian Mess", "Tirunelveli Halwa & Tiffin",
      "Kanyakumari Ocean Treat", "Thanjavur Maratha Kitchen", "Trichy Rockfort Dining", "Chettinad Spices",
      "Spice Symphony Kovai", "The Table RS Puram", "Urban Spoon Restaurant", "The Hearth Kitchen",
      "Oven & Pan Restaurant"
    ];
    const streets = [
      "DB Road", "East TV Swamy Road", "West TV Swamy Road", "Diwan Bahadur Road",
      "Cowley Brown Road", "Lawley Road", "West Club Road", "Light House Road",
      "Sir Shanmugam Road", "Periasamy Road", "Thiruvenkataswamy Road", "McIver Road"
    ];
    const subs = ["South Indian", "North Indian", "Chettinad", "Kongu Cuisine", "Chinese & Asian", "Tiffin & Meals", "Biryani Specialty", "Multi-Cuisine"];
    const name = names[i % names.length] + (i >= names.length ? ` Phase ${Math.floor(i / names.length) + 1}` : "");
    const street = streets[i % streets.length];
    const sub = subs[i % subs.length];
    const hasWeb = idx % 3 === 0;
    const phoneNum = String(idx).padStart(4, "0");
    const padIdx = String(idx).padStart(3, "0");

    return {
      business_name: name,
      category: "Restaurant",
      sub_category: sub,
      phone: `+91 422 244 ${phoneNum}`,
      phone_raw: `+91422244${phoneNum}`,
      website: hasWeb ? `https://${name.toLowerCase().replace(/[^a-z0-9]/g, "")}.com` : null,
      address: `${100 + idx} ${street}, RS Puram, Coimbatore, Tamil Nadu 641002`,
      city: "Coimbatore",
      rating: parseFloat((3.9 + ((idx * 7) % 11) / 10).toFixed(1)),
      reviews: 100 + (idx * 37) % 2500,
      scraped_at: "2025-01-15T11:30:00Z",
      place_id: `ChIJ_RSP_REST_${padIdx}`,
      social_links: hasWeb ? [`https://instagram.com/${name.toLowerCase().replace(/[^a-z0-9]/g, "")}`] : [],
    };
  }),
];

// Additional Deterministic Businesses across other categories and locations
const OTHER_BUSINESSES: RawRecord[] = [
  // Gandhipuram Restaurants
  {
    business_name: "Saravana Bhavan Gandhipuram",
    category: "Restaurant",
    sub_category: "South Indian",
    phone: "+91 422 233 4455",
    phone_raw: "+914222334455",
    website: "https://www.saravanabhavan.com",
    address: "123 Cross Cut Road, Gandhipuram, Coimbatore, Tamil Nadu 641012",
    city: "Coimbatore",
    rating: 4.5,
    reviews: 1250,
    scraped_at: "2025-01-15T10:30:00Z",
    place_id: "ChIJ_GANDHI_REST_001",
    social_links: ["https://facebook.com/saravanabhavan"],
  },
  {
    business_name: "Rayappas Restaurant Gandhipuram",
    category: "Restaurant",
    sub_category: "Multi-Cuisine",
    phone: "+91 422 288 9900",
    phone_raw: "+914222889900",
    website: "https://rayappas.com",
    address: "987 Cross Cut Road, Gandhipuram, Coimbatore, Tamil Nadu 641012",
    city: "Coimbatore",
    rating: 4.4,
    reviews: 678,
    scraped_at: "2025-01-15T10:35:00Z",
    place_id: "ChIJ_GANDHI_REST_002",
    social_links: [],
  },
  // Cafes
  {
    business_name: "The French Door Race Course",
    category: "Cafe",
    sub_category: "Bakery & Cafe",
    phone: "+91 422 300 1122",
    phone_raw: "+914223001122",
    website: "https://thefrenchdoor.in",
    address: "258 Race Course Road, Race Course, Coimbatore, Tamil Nadu 641018",
    city: "Coimbatore",
    rating: 4.8,
    reviews: 567,
    scraped_at: "2025-01-15T10:37:00Z",
    place_id: "ChIJ_CAFE_001",
    social_links: ["https://facebook.com/thefrenchdoor"],
  },
  {
    business_name: "Black Forest Cafe Brookefields",
    category: "Cafe",
    sub_category: "Desserts & Coffee",
    phone: "+91 422 311 2233",
    phone_raw: "+914223112233",
    website: null,
    address: "369 Brookefields, Coimbatore, Tamil Nadu 641006",
    city: "Coimbatore",
    rating: 4.3,
    reviews: 289,
    scraped_at: "2025-01-15T10:38:00Z",
    place_id: "ChIJ_CAFE_002",
    social_links: [],
  },
  {
    business_name: "Cafe Coffee Day Fun Mall",
    category: "Cafe",
    sub_category: "Coffee Shop",
    phone: "+91 422 322 3344",
    phone_raw: "+914223223344",
    website: "https://cafecoffeeday.com",
    address: "741 Fun Mall, Avinashi Road, Peelamedu, Coimbatore, Tamil Nadu 641006",
    city: "Coimbatore",
    rating: 3.9,
    reviews: 234,
    scraped_at: "2025-01-15T10:39:00Z",
    place_id: "ChIJ_CAFE_003",
    social_links: ["https://facebook.com/ccdindia"],
  },
  // Bakeries
  {
    business_name: "KR Bakes Ganapathy",
    category: "Bakery",
    sub_category: "Sweets & Bakery",
    phone: "+91 422 253 1122",
    phone_raw: "+914222531122",
    website: null,
    address: "88 Sathy Road, Ganapathy, Coimbatore, Tamil Nadu 641006",
    city: "Coimbatore",
    rating: 4.2,
    reviews: 340,
    scraped_at: "2025-01-15T10:40:00Z",
    place_id: "ChIJ_BAKERY_001",
    social_links: [],
  },
  // Salon & Fitness
  {
    business_name: "Toni & Guy Saibaba Colony",
    category: "Salon & Fitness",
    sub_category: "Hair Salon",
    phone: "+91 422 243 8899",
    phone_raw: "+914222438899",
    website: "https://toniandguy.com",
    address: "45 NSR Road, Saibaba Colony, Coimbatore, Tamil Nadu 641011",
    city: "Coimbatore",
    rating: 4.6,
    reviews: 520,
    scraped_at: "2025-01-15T10:41:00Z",
    place_id: "ChIJ_SALON_001",
    social_links: [],
  },
];

// Global Mock Businesses across major international tech and business hubs
const GLOBAL_BUSINESSES: RawRecord[] = [
  // New York, USA
  {
    business_name: "Gramercy Tavern",
    category: "Restaurant",
    sub_category: "Contemporary American",
    phone: "+1 212 477 0777",
    phone_raw: "+12124770777",
    website: "https://gramercytavern.com",
    address: "42 E 20th St, New York, NY 10003, USA",
    city: "New York",
    rating: 4.7,
    reviews: 3200,
    scraped_at: "2025-01-15T10:00:00Z",
    place_id: "ChIJ_NYC_REST_001",
    social_links: ["https://instagram.com/gramercytavern"],
  },
  {
    business_name: "Joe's Pizza West Village",
    category: "Restaurant",
    sub_category: "Pizzeria & Italian",
    phone: "+1 212 366 1182",
    phone_raw: "+12123661182",
    website: null,
    address: "7 Carmine St, New York, NY 10014, USA",
    city: "New York",
    rating: 4.8,
    reviews: 5400,
    scraped_at: "2025-01-15T10:01:00Z",
    place_id: "ChIJ_NYC_REST_002",
    social_links: ["https://facebook.com/joespizzanyc"],
  },
  {
    business_name: "Bluestone Lane Manhattan",
    category: "Cafe",
    sub_category: "Specialty Coffee & Brunch",
    phone: "+1 212 555 0192",
    phone_raw: "+12125550192",
    website: "https://bluestonelane.com",
    address: "55 Greenwich Ave, New York, NY 10014, USA",
    city: "New York",
    rating: 4.6,
    reviews: 890,
    scraped_at: "2025-01-15T10:02:00Z",
    place_id: "ChIJ_NYC_CAFE_001",
    social_links: ["https://instagram.com/bluestonelane"],
  },
  {
    business_name: "Levain Bakery Upper West Side",
    category: "Bakery",
    sub_category: "Artisan Cookies & Pastries",
    phone: "+1 212 874 6120",
    phone_raw: "+12128746120",
    website: "https://levainbakery.com",
    address: "167 W 74th St, New York, NY 10023, USA",
    city: "New York",
    rating: 4.9,
    reviews: 4100,
    scraped_at: "2025-01-15T10:03:00Z",
    place_id: "ChIJ_NYC_BAKERY_001",
    social_links: ["https://instagram.com/levainbakery"],
  },
  {
    business_name: "Tribeca Dental Studio",
    category: "Healthcare",
    sub_category: "Dental Clinic",
    phone: "+1 212 555 0184",
    phone_raw: "+12125550184",
    website: null,
    address: "54 Hudson St, New York, NY 10013, USA",
    city: "New York",
    rating: 4.8,
    reviews: 320,
    scraped_at: "2025-01-15T10:04:00Z",
    place_id: "ChIJ_NYC_HEALTH_001",
    social_links: [],
  },
  {
    business_name: "Soho Fitness Club & Spa",
    category: "Salon & Fitness",
    sub_category: "Gym & Wellness",
    phone: "+1 212 555 0198",
    phone_raw: "+12125550198",
    website: "https://sohofitnessnyc.com",
    address: "482 Broome St, New York, NY 10013, USA",
    city: "New York",
    rating: 4.7,
    reviews: 450,
    scraped_at: "2025-01-15T10:05:00Z",
    place_id: "ChIJ_NYC_SALON_001",
    social_links: ["https://instagram.com/sohofitness"],
  },
  {
    business_name: "Hudson Yards Cloud Labs",
    category: "IT Services",
    sub_category: "Software & AI Solutions",
    phone: "+1 212 555 0133",
    phone_raw: "+12125550133",
    website: "https://hudsonyardslabs.io",
    address: "500 W 33rd St, New York, NY 10001, USA",
    city: "New York",
    rating: 4.9,
    reviews: 110,
    scraped_at: "2025-01-15T10:06:00Z",
    place_id: "ChIJ_NYC_IT_001",
    social_links: ["https://linkedin.com/company/hudsonyardslabs"],
  },

  // London, UK
  {
    business_name: "Dishoom Covent Garden",
    category: "Restaurant",
    sub_category: "Bombay Cafe & Dining",
    phone: "+44 20 7420 9320",
    phone_raw: "+442074209320",
    website: "https://dishoom.com",
    address: "12 Upper St Martin's Ln, London WC2H 9FB, UK",
    city: "London",
    rating: 4.7,
    reviews: 4800,
    scraped_at: "2025-01-15T10:10:00Z",
    place_id: "ChIJ_LON_REST_001",
    social_links: ["https://instagram.com/dishoom"],
  },
  {
    business_name: "The Wolseley Piccadilly",
    category: "Restaurant",
    sub_category: "European Grand Cafe",
    phone: "+44 20 7499 6996",
    phone_raw: "+442074996996",
    website: null,
    address: "160 Piccadilly, St. James's, London W1J 9EB, UK",
    city: "London",
    rating: 4.6,
    reviews: 2900,
    scraped_at: "2025-01-15T10:11:00Z",
    place_id: "ChIJ_LON_REST_002",
    social_links: ["https://instagram.com/thewolseley"],
  },
  {
    business_name: "Monmouth Coffee Borough Market",
    category: "Cafe",
    sub_category: "Artisan Coffee",
    phone: "+44 20 7232 3010",
    phone_raw: "+442072323010",
    website: "https://monmouthcoffee.co.uk",
    address: "2 Park St, London SE1 9AB, UK",
    city: "London",
    rating: 4.8,
    reviews: 1950,
    scraped_at: "2025-01-15T10:12:00Z",
    place_id: "ChIJ_LON_CAFE_001",
    social_links: [],
  },
  {
    business_name: "Gail's Bakery Soho",
    category: "Bakery",
    sub_category: "Fresh Bread & Pastries",
    phone: "+44 20 7439 7788",
    phone_raw: "+442074397788",
    website: "https://gailsbread.co.uk",
    address: "128 Wardour St, London W1F 8TN, UK",
    city: "London",
    rating: 4.5,
    reviews: 820,
    scraped_at: "2025-01-15T10:13:00Z",
    place_id: "ChIJ_LON_BAKERY_001",
    social_links: ["https://instagram.com/gailsbakery"],
  },
  {
    business_name: "Harley Street Health Clinic",
    category: "Healthcare",
    sub_category: "Private Medical Practice",
    phone: "+44 20 7935 0022",
    phone_raw: "+442079350022",
    website: null,
    address: "93 Harley St, Marylebone, London W1G 6AD, UK",
    city: "London",
    rating: 4.9,
    reviews: 410,
    scraped_at: "2025-01-15T10:14:00Z",
    place_id: "ChIJ_LON_HEALTH_001",
    social_links: [],
  },
  {
    business_name: "Shoreditch Tech Collective",
    category: "IT Services",
    sub_category: "Digital Agency & Web",
    phone: "+44 20 7033 9000",
    phone_raw: "+442070339000",
    website: "https://shoreditchtech.co.uk",
    address: "24 Old St, London EC1V 9HX, UK",
    city: "London",
    rating: 4.8,
    reviews: 140,
    scraped_at: "2025-01-15T10:15:00Z",
    place_id: "ChIJ_LON_IT_001",
    social_links: ["https://linkedin.com/company/shoreditchtech"],
  },

  // San Francisco, USA
  {
    business_name: "Tartine Bakery & Cafe Mission",
    category: "Bakery",
    sub_category: "Artisan Sourdough & Pastry",
    phone: "+1 415 487 2600",
    phone_raw: "+14154872600",
    website: "https://tartinebakery.com",
    address: "600 Guerrero St, San Francisco, CA 94110, USA",
    city: "San Francisco",
    rating: 4.8,
    reviews: 3800,
    scraped_at: "2025-01-15T10:20:00Z",
    place_id: "ChIJ_SF_BAKERY_001",
    social_links: ["https://instagram.com/tartinebakery"],
  },
  {
    business_name: "State Bird Provisions Fillmore",
    category: "Restaurant",
    sub_category: "Californian Dim Sum Style",
    phone: "+1 415 795 1272",
    phone_raw: "+14157951272",
    website: "https://statebirdsf.com",
    address: "1529 Fillmore St, San Francisco, CA 94115, USA",
    city: "San Francisco",
    rating: 4.7,
    reviews: 2100,
    scraped_at: "2025-01-15T10:21:00Z",
    place_id: "ChIJ_SF_REST_001",
    social_links: ["https://instagram.com/statebirdprovisions"],
  },
  {
    business_name: "Philz Coffee SOMA",
    category: "Cafe",
    sub_category: "Specialty Custom Drips",
    phone: "+1 415 875 9943",
    phone_raw: "+14158759943",
    website: null,
    address: "201 Berry St, San Francisco, CA 94158, USA",
    city: "San Francisco",
    rating: 4.6,
    reviews: 1420,
    scraped_at: "2025-01-15T10:22:00Z",
    place_id: "ChIJ_SF_CAFE_001",
    social_links: ["https://facebook.com/philzcoffee"],
  },
  {
    business_name: "SOMA Edge AI & Cloud Labs",
    category: "IT Services",
    sub_category: "AI & Full-Stack Development",
    phone: "+1 415 555 0122",
    phone_raw: "+14155550122",
    website: "https://somaedge.ai",
    address: "548 Market St, San Francisco, CA 94104, USA",
    city: "San Francisco",
    rating: 4.9,
    reviews: 210,
    scraped_at: "2025-01-15T10:23:00Z",
    place_id: "ChIJ_SF_IT_001",
    social_links: ["https://linkedin.com/company/somaedgeai"],
  },

  // Tokyo, Japan
  {
    business_name: "Sukiyabashi Dining Ginza",
    category: "Restaurant",
    sub_category: "Authentic Japanese & Sushi",
    phone: "+81 3 3535 3600",
    phone_raw: "+81335353600",
    website: "https://sushi-jiro.jp",
    address: "4-2-15 Ginza, Chuo City, Tokyo 104-0061, Japan",
    city: "Tokyo",
    rating: 4.9,
    reviews: 2800,
    scraped_at: "2025-01-15T10:25:00Z",
    place_id: "ChIJ_TYO_REST_001",
    social_links: [],
  },
  {
    business_name: "Fuglen Tokyo Shibuya",
    category: "Cafe",
    sub_category: "Nordic Roast & Cocktails",
    phone: "+81 3 6804 9228",
    phone_raw: "+81368049228",
    website: null,
    address: "1-16-11 Tomigaya, Shibuya City, Tokyo 151-0063, Japan",
    city: "Tokyo",
    rating: 4.6,
    reviews: 1680,
    scraped_at: "2025-01-15T10:26:00Z",
    place_id: "ChIJ_TYO_CAFE_001",
    social_links: ["https://instagram.com/fuglentokyo"],
  },
  {
    business_name: "Akihabara NextGen Cloud Solutions",
    category: "IT Services",
    sub_category: "Enterprise Cloud & Software",
    phone: "+81 3 5298 2200",
    phone_raw: "+81352982200",
    website: "https://akihabaracloud.co.jp",
    address: "1-18-13 Sotokanda, Chiyoda City, Tokyo 101-0021, Japan",
    city: "Tokyo",
    rating: 4.8,
    reviews: 190,
    scraped_at: "2025-01-15T10:27:00Z",
    place_id: "ChIJ_TYO_IT_001",
    social_links: [],
  },

  // Dubai, UAE
  {
    business_name: "Zuma Restaurant DIFC",
    category: "Restaurant",
    sub_category: "Contemporary Japanese & Grill",
    phone: "+971 4 425 5660",
    phone_raw: "+97144255660",
    website: "https://zumarestaurant.com/dubai",
    address: "Gate Village 06, DIFC, Dubai, UAE",
    city: "Dubai",
    rating: 4.8,
    reviews: 4300,
    scraped_at: "2025-01-15T10:30:00Z",
    place_id: "ChIJ_DXB_REST_001",
    social_links: ["https://instagram.com/zumadubai"],
  },
  {
    business_name: "Arabian Tea House Al Fahidi",
    category: "Cafe",
    sub_category: "Emirati Heritage Cafe",
    phone: "+971 4 353 5071",
    phone_raw: "+97143535071",
    website: null,
    address: "Bastakiya Opposite Musalla, Dubai, UAE",
    city: "Dubai",
    rating: 4.7,
    reviews: 3100,
    scraped_at: "2025-01-15T10:31:00Z",
    place_id: "ChIJ_DXB_CAFE_001",
    social_links: ["https://instagram.com/arabianteahouse"],
  },
  {
    business_name: "Dubai Marina Polyclinic & Wellness",
    category: "Healthcare",
    sub_category: "Specialized Medical Services",
    phone: "+971 4 399 7777",
    phone_raw: "+97143997777",
    website: "https://marinapolyclinic.ae",
    address: "Marina Diamond 2, Dubai Marina, Dubai, UAE",
    city: "Dubai",
    rating: 4.7,
    reviews: 480,
    scraped_at: "2025-01-15T10:32:00Z",
    place_id: "ChIJ_DXB_HEALTH_001",
    social_links: [],
  },

  // Toronto, Canada
  {
    business_name: "Pai Northern Thai Kitchen",
    category: "Restaurant",
    sub_category: "Authentic Thai & Asian",
    phone: "+1 416 901 4724",
    phone_raw: "+14169014724",
    website: "https://paitoronto.com",
    address: "18 Duncan St, Toronto, ON M5H 3G8, Canada",
    city: "Toronto",
    rating: 4.8,
    reviews: 4900,
    scraped_at: "2025-01-15T10:35:00Z",
    place_id: "ChIJ_TOR_REST_001",
    social_links: ["https://instagram.com/paitoronto"],
  },
  {
    business_name: "Balzac's Distillery District",
    category: "Cafe",
    sub_category: "Artisan Coffee Roastery",
    phone: "+1 416 207 1709",
    phone_raw: "+14162071709",
    website: null,
    address: "1 Trinity St, Toronto, ON M5A 3C4, Canada",
    city: "Toronto",
    rating: 4.6,
    reviews: 1250,
    scraped_at: "2025-01-15T10:36:00Z",
    place_id: "ChIJ_TOR_CAFE_001",
    social_links: ["https://instagram.com/balzacscoffee"],
  },
  {
    business_name: "Bay Street Software Systems",
    category: "IT Services",
    sub_category: "Enterprise Fintech & Cloud",
    phone: "+1 416 555 0111",
    phone_raw: "+14165550111",
    website: "https://baystreetsoftware.ca",
    address: "100 King St W, Toronto, ON M5X 1A9, Canada",
    city: "Toronto",
    rating: 4.9,
    reviews: 180,
    scraped_at: "2025-01-15T10:37:00Z",
    place_id: "ChIJ_TOR_IT_001",
    social_links: ["https://linkedin.com/company/baystreetsoftware"],
  },

  // Sydney, Australia
  {
    business_name: "Bills Bondi Beach",
    category: "Restaurant",
    sub_category: "Modern Australian Dining",
    phone: "+61 2 8412 0700",
    phone_raw: "+61284120700",
    website: "https://bills.com.au",
    address: "79 Hall St, Bondi Beach, Sydney NSW 2026, Australia",
    city: "Sydney",
    rating: 4.7,
    reviews: 2600,
    scraped_at: "2025-01-15T10:40:00Z",
    place_id: "ChIJ_SYD_REST_001",
    social_links: ["https://instagram.com/billsaustralia"],
  },
  {
    business_name: "Single O Surry Hills",
    category: "Cafe",
    sub_category: "Specialty Pour-Over & Brews",
    phone: "+61 2 9211 0665",
    phone_raw: "+61292110665",
    website: null,
    address: "60-64 Reservoir St, Surry Hills, Sydney NSW 2010, Australia",
    city: "Sydney",
    rating: 4.7,
    reviews: 1540,
    scraped_at: "2025-01-15T10:41:00Z",
    place_id: "ChIJ_SYD_CAFE_001",
    social_links: ["https://instagram.com/single_o"],
  },
  {
    business_name: "Darlinghurst Creative & Tech Agency",
    category: "IT Services",
    sub_category: "Web & Mobile Product Engineering",
    phone: "+61 2 9331 4444",
    phone_raw: "+61293314444",
    website: "https://darlinghursttech.com.au",
    address: "182 Campbell St, Surry Hills, Sydney NSW 2010, Australia",
    city: "Sydney",
    rating: 4.8,
    reviews: 95,
    scraped_at: "2025-01-15T10:42:00Z",
    place_id: "ChIJ_SYD_IT_001",
    social_links: ["https://linkedin.com/company/darlinghursttech"],
  },

  // Paris, France
  {
    business_name: "Le Comptoir du Relais Saint-Germain",
    category: "Restaurant",
    sub_category: "Bistro & French Gastronomy",
    phone: "+33 1 44 27 07 97",
    phone_raw: "+33144270797",
    website: "https://hotel-paris-relais-saint-germain.com",
    address: "9 Carrefour de l'Odeon, 75006 Paris, France",
    city: "Paris",
    rating: 4.6,
    reviews: 2700,
    scraped_at: "2025-01-15T10:45:00Z",
    place_id: "ChIJ_PAR_REST_001",
    social_links: [],
  },
  {
    business_name: "Cafe de Flore Saint-Germain",
    category: "Cafe",
    sub_category: "Historic Parisian Cafe",
    phone: "+33 1 45 48 55 26",
    phone_raw: "+33145485526",
    website: null,
    address: "172 Bd Saint-Germain, 75006 Paris, France",
    city: "Paris",
    rating: 4.5,
    reviews: 4200,
    scraped_at: "2025-01-15T10:46:00Z",
    place_id: "ChIJ_PAR_CAFE_001",
    social_links: ["https://instagram.com/lecafedeflore"],
  },

  // Singapore
  {
    business_name: "Jumbo Seafood East Coast",
    category: "Restaurant",
    sub_category: "Seafood & Local Dining",
    phone: "+65 6442 3435",
    phone_raw: "+6564423435",
    website: "https://jumboseafood.com.sg",
    address: "1206 East Coast Parkway, #01-07/08, Singapore 449883",
    city: "Singapore",
    rating: 4.7,
    reviews: 5800,
    scraped_at: "2025-01-15T10:50:00Z",
    place_id: "ChIJ_SIN_REST_001",
    social_links: ["https://instagram.com/jumboseafoodsg"],
  },
  {
    business_name: "Chye Seng Huat Hardware Roastery",
    category: "Cafe",
    sub_category: "Specialty Coffee Roastery",
    phone: "+65 6396 0609",
    phone_raw: "+6563960609",
    website: null,
    address: "150 Tyrwhitt Rd, Singapore 207563",
    city: "Singapore",
    rating: 4.6,
    reviews: 2100,
    scraped_at: "2025-01-15T10:51:00Z",
    place_id: "ChIJ_SIN_CAFE_001",
    social_links: ["https://instagram.com/cshhcoffee"],
  },
  {
    business_name: "Marina Bay AI & Cloud Solutions",
    category: "IT Services",
    sub_category: "AI, FinTech & Enterprise Software",
    phone: "+65 6789 0123",
    phone_raw: "+6567890123",
    website: "https://marinabaytech.sg",
    address: "10 Marina Blvd, Marina Bay Financial Centre, Singapore 018983",
    city: "Singapore",
    rating: 4.9,
    reviews: 240,
    scraped_at: "2025-01-15T10:52:00Z",
    place_id: "ChIJ_SIN_IT_001",
    social_links: ["https://linkedin.com/company/marinabaytech"],
  },

  // Berlin, Germany
  {
    business_name: "The Barn Coffee Roasters Mitte",
    category: "Cafe",
    sub_category: "Specialty Coffee Roastery",
    phone: "+49 30 28042424",
    phone_raw: "+493028042424",
    website: "https://thebarn.de",
    address: "Auguststraße 58, 10119 Berlin, Germany",
    city: "Berlin",
    rating: 4.7,
    reviews: 1890,
    scraped_at: "2025-01-15T10:55:00Z",
    place_id: "ChIJ_BER_CAFE_001",
    social_links: ["https://instagram.com/thebarnberlin"],
  },
  {
    business_name: "Kreuzberg Digital Systems GmbH",
    category: "IT Services",
    sub_category: "Modern Web & Cloud Architecture",
    phone: "+49 30 12345678",
    phone_raw: "+493012345678",
    website: null,
    address: "Oranienstraße 185, 10999 Berlin, Germany",
    city: "Berlin",
    rating: 4.8,
    reviews: 120,
    scraped_at: "2025-01-15T10:56:00Z",
    place_id: "ChIJ_BER_IT_001",
    social_links: [],
  },

  // Mumbai, India
  {
    business_name: "The Bombay Canteen Lower Parel",
    category: "Restaurant",
    sub_category: "Regional Indian Gastronomy",
    phone: "+91 22 4966 6666",
    phone_raw: "+912249666666",
    website: "https://thebombaycanteen.com",
    address: "Unit 1, Process House, Kamala Mills, Lower Parel, Mumbai 400013, India",
    city: "Mumbai",
    rating: 4.8,
    reviews: 4200,
    scraped_at: "2025-01-15T11:00:00Z",
    place_id: "ChIJ_BOM_REST_001",
    social_links: ["https://instagram.com/thebombaycanteen"],
  },
  {
    business_name: "Blue Tokai Coffee Roasters Bandra",
    category: "Cafe",
    sub_category: "Specialty Indian Roastery",
    phone: "+91 22 2640 1234",
    phone_raw: "+912226401234",
    website: "https://bluetokaicoffee.com",
    address: "Perry Cross Rd, Pali Hill, Bandra West, Mumbai 400050, India",
    city: "Mumbai",
    rating: 4.7,
    reviews: 1650,
    scraped_at: "2025-01-15T11:01:00Z",
    place_id: "ChIJ_BOM_CAFE_001",
    social_links: ["https://instagram.com/bluetokaicoffee"],
  },
];

export const MOCK_BUSINESSES: RawRecord[] = [
  ...GLOBAL_BUSINESSES,
  ...RS_PURAM_RESTAURANTS,
  ...OTHER_BUSINESSES,
];

/**
 * Dynamically synthesizes realistic business leads for ANY location worldwide and category.
 * Used when querying mock mode with custom cities or when more mock leads are needed.
 */
export function generateDynamicMockBusinesses(
  category: string,
  location: string,
  count: number,
  offset = 0
): RawRecord[] {
  const normCat = (category || "General").trim();
  const normLoc = (location || "Global").trim();
  const city = normLoc.split(",")[0].trim() || "Global City";
  const countryOrRegion = normLoc.includes(",") ? normLoc.split(",").slice(1).join(",").trim() : "International";

  const prefixes = [
    "Apex", "Prime", "Summit", "Heritage", "Metro", "Vanguard", "Urban",
    "Starlight", "Beacon", "Crown", "Nexus", "Horizon", "Grand", "Boutique",
    "Signature", "Pioneer", "Artisan", "Echo", "Lumina", "Zenith",
  ];

  const categoryAdjectives: Record<string, string[]> = {
    restaurant: ["Gourmet Kitchen", "Bistro & Bar", "Dining House", "Eatery", "Grill & Table", "Culinary House"],
    cafe: ["Coffee Roasters", "Artisan Espresso", "Cafe & Lounge", "Brew Bar", "Morning Club"],
    bakery: ["Artisan Bakes", "Pastry & Bread Studio", "Sweet Boutique", "Bakehouse", "Patisserie"],
    healthcare: ["Wellness Clinic", "Medical Care Group", "Health & Dental Studio", "Polyclinic", "Family Practice"],
    "salon & fitness": ["Studio & Spa", "Fitness Collective", "Health Club & Yoga", "Wellness Spa", "Barber & Lounge"],
    retail: ["Flagship Store", "Boutique Collection", "Fashion & Lifestyle", "Goods Co.", "Department Outlet"],
    automobile: ["Auto Service Center", "Precision Motors", "EV & Tuning Hub", "Car Care Studio", "Motor Works"],
    "it services": ["Cloud Innovations", "Digital & AI Systems", "Software Labs", "Tech Partners", "NextGen Solutions"],
  };

  const catLower = normCat.toLowerCase();
  const matchedSuffixes = Object.entries(categoryAdjectives).find(([key]) => catLower.includes(key))?.[1] || [
    "Services & Co.", "Solutions Group", "Enterprises", "Studio", "Associates"
  ];

  const results: RawRecord[] = [];

  for (let i = 0; i < count; i++) {
    const idx = offset + i;
    const prefix = prefixes[idx % prefixes.length];
    const suffix = matchedSuffixes[idx % matchedSuffixes.length];
    const businessName = `${prefix} ${city} ${suffix}`;
    const slug = businessName.toLowerCase().replace(/[^a-z0-9]+/g, "-");
    const hasWebsite = idx % 3 !== 0; // 33% opportunity without existing site
    const streetNumber = 10 + ((idx * 17) % 890);
    const streetNames = ["Main St", "High St", "Commercial Blvd", "Central Ave", "Grand Way", "Market St", "Ocean Drive", "Park Ave"];
    const street = streetNames[idx % streetNames.length];
    const rating = Math.min(5.0, Math.round((4.0 + ((idx * 7) % 10) * 0.1) * 10) / 10);
    const reviews = 45 + ((idx * 83) % 1400);

    results.push({
      business_name: businessName,
      category: normCat,
      sub_category: `${normCat} & Local Services`,
      phone: `+1 ${200 + (idx % 800)} 555 ${String(1000 + (idx % 9000)).padStart(4, "0")}`,
      phone_raw: `+1${200 + (idx % 800)}555${String(1000 + (idx % 9000)).padStart(4, "0")}`,
      website: hasWebsite ? `https://${slug}.com` : null,
      address: `${streetNumber} ${street}, ${normLoc}`,
      city,
      rating,
      reviews,
      scraped_at: new Date(Date.now() - (idx * 3600000)).toISOString(),
      place_id: `ChIJ_DYN_${slug.slice(0, 16)}_${idx}`,
      social_links: hasWebsite ? [`https://instagram.com/${slug}`] : [],
    });
  }

  return results;
}

