import { TemplateDefinition, TemplateType } from "../types";
import { THEMES } from "../themes";

export const TEMPLATES: Record<TemplateType, TemplateDefinition> = {
  restaurant: {
    id: "restaurant",
    name: "Restaurant & Mess",
    description: "Full-service dining with verified menu, culinary highlights, Google reviews, and table reservations",
    pages: ["index", "contact"],
    sections: [
      { id: "hero", type: "hero", required: true, order: 1, title: "Welcome" },
      { id: "about", type: "about", required: true, order: 2, title: "Our Story" },
      { id: "menu", type: "menu", required: true, order: 3, title: "Our Menu & Specialties" },
      { id: "gallery", type: "gallery", required: false, order: 4, title: "Gallery" },
      { id: "testimonials", type: "testimonials", required: true, order: 5, title: "Guest Reviews" },
      { id: "hours", type: "hours", required: true, order: 6, title: "Operating Hours" },
      { id: "contact", type: "contact", required: true, order: 7, title: "Find Us" },
      { id: "cta", type: "cta", required: true, order: 8, title: "Reserve Table" },
    ],
    categoryKeywords: [
      "restaurant",
      "mess",
      "bistro",
      "diner",
      "eatery",
      "kitchen",
      "grill",
      "pizza",
      "burger",
      "biryani",
      "vegetarian",
      "veg",
      "non-veg",
      "dining",
      "food",
      "bar & grill",
      "tandoori",
      "dhaba",
      "caterer",
      "catering",
      "cuisine",
      "indian restaurant",
      "south indian",
      "north indian",
    ],
    defaultTheme: THEMES.restaurant,
  },
  cafe: {
    id: "cafe",
    name: "Cafe & Bakery",
    description: "Coffee shop & bakery with artisan brews, freshly baked treats, and takeaway orders",
    pages: ["index", "contact"],
    sections: [
      { id: "hero", type: "hero", required: true, order: 1, title: "Welcome" },
      { id: "about", type: "about", required: true, order: 2, title: "About Our Cafe" },
      { id: "menu", type: "menu", required: true, order: 3, title: "Brews & Bakes" },
      { id: "gallery", type: "gallery", required: true, order: 4, title: "Ambiance" },
      { id: "testimonials", type: "testimonials", required: true, order: 5, title: "Customer Reviews" },
      { id: "hours", type: "hours", required: true, order: 6, title: "Cafe Hours" },
      { id: "contact", type: "contact", required: true, order: 7, title: "Visit Us" },
      { id: "cta", type: "cta", required: true, order: 8, title: "Order Now" },
    ],
    categoryKeywords: [
      "cafe",
      "coffee",
      "coffee shop",
      "bakery",
      "pastry",
      "brunch",
      "tea",
      "espresso",
      "dessert",
      "bakes",
      "patisserie",
      "sweet shop",
    ],
    defaultTheme: THEMES.cafe,
  },
  hotel: {
    id: "hotel",
    name: "Hotel & Resort",
    description: "Luxury hotel & resort with room categories, verified amenities, guest reviews, and direct booking inquiries",
    pages: ["index", "contact"],
    sections: [
      { id: "hero", type: "hero", required: true, order: 1, title: "Experience Hospitality" },
      { id: "about", type: "about", required: true, order: 2, title: "About the Property" },
      { id: "services", type: "services", required: true, order: 3, title: "Accommodations & Amenities" },
      { id: "gallery", type: "gallery", required: true, order: 4, title: "Property Showcase" },
      { id: "testimonials", type: "testimonials", required: true, order: 5, title: "Guest Reviews" },
      { id: "contact", type: "contact", required: true, order: 6, title: "Location & Directions" },
      { id: "cta", type: "cta", required: true, order: 7, title: "Book Your Stay" },
    ],
    categoryKeywords: [
      "hotel",
      "resort",
      "lodge",
      "lodging",
      "inn",
      "motel",
      "homestay",
      "guest house",
      "stay",
      "suites",
      "rooms",
      "hospitality",
      "villa",
      "cottage",
    ],
    defaultTheme: THEMES.hotel,
  },
  salon: {
    id: "salon",
    name: "Salon & Beauty",
    description: "Beauty salon & grooming studio with service menu, lookbook, and appointment booking",
    pages: ["index", "contact"],
    sections: [
      { id: "hero", type: "hero", required: true, order: 1, title: "Welcome" },
      { id: "about", type: "about", required: true, order: 2, title: "About Our Salon" },
      { id: "services", type: "services", required: true, order: 3, title: "Styling & Beauty Services" },
      { id: "gallery", type: "gallery", required: true, order: 4, title: "Lookbook" },
      { id: "team", type: "team", required: false, order: 5, title: "Stylists" },
      { id: "testimonials", type: "testimonials", required: true, order: 6, title: "Client Reviews" },
      { id: "hours", type: "hours", required: true, order: 7, title: "Hours" },
      { id: "contact", type: "contact", required: true, order: 8, title: "Location" },
      { id: "cta", type: "cta", required: true, order: 9, title: "Book Appointment" },
    ],
    categoryKeywords: [
      "salon",
      "beauty",
      "hair",
      "haircut",
      "nail",
      "barber",
      "barbershop",
      "unisex",
      "bridal",
      "facial",
      "makeup",
      "grooming",
      "parlour",
    ],
    defaultTheme: THEMES.salon,
  },
  spa: {
    id: "spa",
    name: "Spa & Wellness",
    description: "Rejuvenating wellness spa with therapeutic treatments, serene ambiance, and therapy reservations",
    pages: ["index", "contact"],
    sections: [
      { id: "hero", type: "hero", required: true, order: 1, title: "Rejuvenate Your Senses" },
      { id: "about", type: "about", required: true, order: 2, title: "Our Wellness Sanctuary" },
      { id: "services", type: "services", required: true, order: 3, title: "Therapies & Treatments" },
      { id: "gallery", type: "gallery", required: true, order: 4, title: "Spa Ambiance" },
      { id: "testimonials", type: "testimonials", required: true, order: 5, title: "Guest Experiences" },
      { id: "hours", type: "hours", required: true, order: 6, title: "Spa Hours" },
      { id: "contact", type: "contact", required: true, order: 7, title: "Location" },
      { id: "cta", type: "cta", required: true, order: 8, title: "Reserve a Session" },
    ],
    categoryKeywords: [
      "spa",
      "wellness",
      "massage",
      "massage parlour",
      "ayurvedic spa",
      "aromatherapy",
      "reflexology",
      "body scrub",
      "sauna",
      "steam bath",
      "rejuvenation",
      "holistic",
    ],
    defaultTheme: THEMES.spa,
  },
  gym: {
    id: "gym",
    name: "Gym & Fitness",
    description: "Fitness center with workout programs, equipment showcase, and membership pass",
    pages: ["index", "contact"],
    sections: [
      { id: "hero", type: "hero", required: true, order: 1, title: "Ignite Your Fitness" },
      { id: "about", type: "about", required: true, order: 2, title: "Why Choose Us" },
      { id: "services", type: "services", required: true, order: 3, title: "Training Programs" },
      { id: "gallery", type: "gallery", required: true, order: 4, title: "Facility & Equipment" },
      { id: "testimonials", type: "testimonials", required: true, order: 5, title: "Member Reviews" },
      { id: "hours", type: "hours", required: true, order: 6, title: "Gym Hours" },
      { id: "contact", type: "contact", required: true, order: 7, title: "Location & Gym Desk" },
      { id: "cta", type: "cta", required: true, order: 8, title: "Start Your Free Pass" },
    ],
    categoryKeywords: [
      "gym",
      "fitness",
      "workout",
      "training",
      "crossfit",
      "yoga",
      "pilates",
      "personal training",
      "zumba",
      "health club",
      "bodybuilding",
      "martial arts",
      "mma",
      "boxing",
    ],
    defaultTheme: THEMES.gym,
  },
  tattoo: {
    id: "tattoo",
    name: "Tattoo Studio",
    description: "Tattoo & piercing studio with portfolio gallery, custom design showcase, and consultation CTA",
    pages: ["index", "contact"],
    sections: [
      { id: "hero", type: "hero", required: true, order: 1, title: "Custom Ink & Artistry" },
      { id: "about", type: "about", required: true, order: 2, title: "Studio Philosophy" },
      { id: "gallery", type: "gallery", required: true, order: 3, title: "Portfolio Gallery" },
      { id: "services", type: "services", required: true, order: 4, title: "Tattoo & Piercing Services" },
      { id: "testimonials", type: "testimonials", required: true, order: 5, title: "Client Stories" },
      { id: "hours", type: "hours", required: false, order: 6, title: "Studio Hours" },
      { id: "contact", type: "contact", required: true, order: 7, title: "Visit Studio" },
      { id: "cta", type: "cta", required: true, order: 8, title: "Book a Consultation" },
    ],
    categoryKeywords: [
      "tattoo",
      "tattoo studio",
      "ink",
      "body art",
      "piercing",
      "artist",
      "tattooing",
    ],
    defaultTheme: THEMES.tattoo,
  },
  clinic: {
    id: "clinic",
    name: "Clinic & Healthcare",
    description: "Medical clinic with patient services, consultation hours, and appointment requests",
    pages: ["index", "contact"],
    sections: [
      { id: "hero", type: "hero", required: true, order: 1, title: "Compassionate Care" },
      { id: "about", type: "about", required: true, order: 2, title: "About Our Practice" },
      { id: "services", type: "services", required: true, order: 3, title: "Clinical Services" },
      { id: "testimonials", type: "testimonials", required: true, order: 4, title: "Patient Feedback" },
      { id: "hours", type: "hours", required: true, order: 5, title: "Consultation Hours" },
      { id: "contact", type: "contact", required: true, order: 6, title: "Clinic Address & Contact" },
      { id: "cta", type: "cta", required: true, order: 7, title: "Request Appointment" },
    ],
    categoryKeywords: [
      "clinic",
      "hospital",
      "dental",
      "dentist",
      "doctor",
      "medical",
      "healthcare",
      "physiotherapy",
      "ayurvedic",
      "health center",
      "optician",
      "dermatology",
      "pediatric",
      "wellness clinic",
      "pharmacy",
      "diagnostic",
      "orthopedic",
    ],
    defaultTheme: THEMES.clinic,
  },
  retail: {
    id: "retail",
    name: "Retail Store & Boutique",
    description: "Retail storefront with product collections, featured items, store hours, and in-store inquiries",
    pages: ["index", "contact"],
    sections: [
      { id: "hero", type: "hero", required: true, order: 1, title: "Welcome to Our Store" },
      { id: "about", type: "about", required: true, order: 2, title: "About Our Brand" },
      { id: "services", type: "services", required: true, order: 3, title: "Featured Collections & Categories" },
      { id: "gallery", type: "gallery", required: true, order: 4, title: "Store Showcase" },
      { id: "testimonials", type: "testimonials", required: true, order: 5, title: "Customer Reviews" },
      { id: "hours", type: "hours", required: true, order: 6, title: "Store Hours" },
      { id: "contact", type: "contact", required: true, order: 7, title: "Store Location" },
      { id: "cta", type: "cta", required: true, order: 8, title: "Visit Store Today" },
    ],
    categoryKeywords: [
      "store",
      "retail",
      "shop",
      "boutique",
      "supermarket",
      "grocery",
      "jewelry",
      "jewellers",
      "fashion",
      "apparel",
      "clothing",
      "electronics",
      "hardware store",
      "gift shop",
      "showroom",
      "mart",
      "footwear",
      "opticals",
    ],
    defaultTheme: THEMES.retail,
  },
  professional: {
    id: "professional",
    name: "Professional & Consulting Services",
    description: "Corporate consulting, legal, accounting, and creative agency services with consultation booking",
    pages: ["index", "contact"],
    sections: [
      { id: "hero", type: "hero", required: true, order: 1, title: "Strategic Expertise" },
      { id: "about", type: "about", required: true, order: 2, title: "About the Practice" },
      { id: "services", type: "services", required: true, order: 3, title: "Practice Areas & Capabilities" },
      { id: "testimonials", type: "testimonials", required: true, order: 4, title: "Client Trust" },
      { id: "hours", type: "hours", required: false, order: 5, title: "Office Hours" },
      { id: "contact", type: "contact", required: true, order: 6, title: "Office Location" },
      { id: "cta", type: "cta", required: true, order: 7, title: "Schedule Consultation" },
    ],
    categoryKeywords: [
      "consulting",
      "consultant",
      "lawyer",
      "legal",
      "advocate",
      "law firm",
      "accountant",
      "accounting",
      "tax",
      "audit",
      "ca firm",
      "chartered accountant",
      "agency",
      "marketing agency",
      "design agency",
      "architecture",
      "architect",
      "engineering firm",
      "financial advisor",
      "real estate agency",
      "realtor",
      "software",
    ],
    defaultTheme: THEMES.professional,
  },
  generic: {
    id: "generic",
    name: "Local Business & Trades",
    description: "Professional responsive website for local trades, repair services, contractors, and local business",
    pages: ["index", "contact"],
    sections: [
      { id: "hero", type: "hero", required: true, order: 1, title: "Welcome" },
      { id: "about", type: "about", required: true, order: 2, title: "About Us" },
      { id: "services", type: "services", required: true, order: 3, title: "Our Services" },
      { id: "testimonials", type: "testimonials", required: true, order: 4, title: "Customer Reviews" },
      { id: "hours", type: "hours", required: false, order: 5, title: "Business Hours" },
      { id: "contact", type: "contact", required: true, order: 6, title: "Contact Us" },
      { id: "cta", type: "cta", required: true, order: 7, title: "Get in Touch" },
    ],
    categoryKeywords: [
      "service",
      "repair",
      "maintenance",
      "cleaning",
      "plumber",
      "plumbing",
      "electrician",
      "electrical",
      "contractor",
      "mechanic",
      "auto repair",
      "car service",
      "packaging",
      "manufacturing",
      "school",
      "education",
      "pest control",
      "carpenter",
      "painter",
    ],
    defaultTheme: THEMES.generic,
  },
  "local-service": {
    id: "local-service",
    name: "Local Service",
    description: "General local service business",
    pages: ["index", "contact"],
    sections: [
      { id: "hero", type: "hero", required: true, order: 1, title: "Welcome" },
      { id: "about", type: "about", required: true, order: 2, title: "About Us" },
      { id: "services", type: "services", required: true, order: 3, title: "Our Services" },
      { id: "testimonials", type: "testimonials", required: true, order: 4, title: "Customer Reviews" },
      { id: "hours", type: "hours", required: false, order: 5, title: "Business Hours" },
      { id: "contact", type: "contact", required: true, order: 6, title: "Contact Us" },
      { id: "cta", type: "cta", required: true, order: 7, title: "Get in Touch" },
    ],
    categoryKeywords: ["service", "repair", "contractor", "maintenance"],
    defaultTheme: THEMES["local-service"],
  },
};

function matchesKeyword(text: string, keyword: string): boolean {
  const escaped = keyword.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const regex = new RegExp(`(^|[^a-z0-9])${escaped}([^a-z0-9]|$)`, "i");
  return regex.test(text);
}

export function selectTemplate(category: string, subCategory?: string): TemplateType {
  const searchText = `${category || ""} ${subCategory || ""}`.toLowerCase();

  // Specific priority check for specific categories before generic
  const priorityOrder: TemplateType[] = [
    "restaurant",
    "cafe",
    "hotel",
    "salon",
    "spa",
    "gym",
    "tattoo",
    "clinic",
    "retail",
    "professional",
  ];

  for (const templateId of priorityOrder) {
    const template = TEMPLATES[templateId];
    if (!template) continue;
    for (const keyword of template.categoryKeywords) {
      if (matchesKeyword(searchText, keyword)) {
        return templateId;
      }
    }
  }

  // Fallback to generic local business template
  return "generic";
}

export function getTemplate(templateId: TemplateType | string): TemplateDefinition {
  const normalized = (templateId || "").toLowerCase();
  if (normalized === "local-service") {
    return TEMPLATES["local-service"] ?? TEMPLATES.generic;
  }
  return TEMPLATES[normalized as TemplateType] ?? TEMPLATES.generic;
}

export function listTemplates(): TemplateDefinition[] {
  return [
    TEMPLATES.restaurant,
    TEMPLATES.cafe,
    TEMPLATES.hotel,
    TEMPLATES.salon,
    TEMPLATES.spa,
    TEMPLATES.gym,
    TEMPLATES.tattoo,
    TEMPLATES.clinic,
    TEMPLATES.retail,
    TEMPLATES.professional,
    TEMPLATES.generic,
  ];
}
